# Generated by Django 5.2.17 on 2026-09-24 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del hábito')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('frequency', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKDAYS', 'Días hábiles'), ('WEEKENDS', 'Fines de semana'), ('CUSTOM', 'Personalizado')], default='DAILY', max_length=20)),
                ('goal_type', models.CharField(choices=[('BOOL', 'Completado / No completado'), ('NUM', 'Meta numérica')], default='BOOL', max_length=10)),
                ('target_value', models.PositiveIntegerField(default=1, help_text='Meta diaria (ej: 1 si es booleano, o cantidad de páginas, minutos, etc.)')),
                ('unit', models.CharField(blank=True, help_text='Ej: páginas, litros, minutos', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha del registro')),
                ('completed', models.BooleanField(default=False)),
                ('actual_value', models.PositiveIntegerField(default=0, help_text='Valor alcanzado en el día')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
